"""Initial migration

Revision ID: 14144185dbe7
Revises: 1ce0d4c92049
Create Date: 2024-06-12 07:13:43.645202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14144185dbe7'
down_revision: Union[str, None] = '1ce0d4c92049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('map_url', sa.String(length=355), nullable=True))
    op.drop_column('events', 'maps_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('maps_url', sa.VARCHAR(length=355), nullable=True))
    op.drop_column('events', 'map_url')
    # ### end Alembic commands ###
